name: DEPLOY AZURE FRANCISCO

on:
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install project dependencies
        run: npm install --legacy-peer-deps
        
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core @actions/http-client --legacy-peer-deps
        
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
           script: |
               const coredemo = require('@actions/core')
               return await coredemo.getIDToken()
           result-encoding: string

      - name: Build Angular App
        run: npm run build --prod

      - name: Generate Static Web App Config
        run: |
          mkdir -p dist/maquinas/browser
          echo '{
            "navigationFallback": {
              "rewrite": "/index.html",
              "exclude": ["/images/*.{png,jpg,gif}", "/css/*"]
            }
          }' > dist/maquinas/browser/staticwebapp.config.json

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_SMOKE_0B3E9EB0F }}
          action: "upload"
          app_location: "." 
          api_location: "" 
          output_location: "dist/maquinas/browser/" 
          github_id_token: ${{ steps.idtoken.outputs.result }}



